### ISSUE TITLE
yarn dev error

### ISSUE THREAD

**Issue by wiiler** [treetips/typescript-nextjs-redux-material-ui-example#32]
![image](https://user-images.githubusercontent.com/9715482/82005340-b474c100-9697-11ea-9ad7-b6e38998e52b.png)

**Comment by treetips** [comment]
@wiiler Thank you for contacting me.

This repository is `typescript-nextjs-redux-material-ui-example`, but the screenshot is [typescript-nextjs-redux-toolkit-material-ui-example](https://github.com/treetips/typescript-nextjs-redux-toolkit-material-ui-example) , so please check it again.

Also, updating `next-redux-wrapper` to version `6.0.0` seems to change the use of the store significantly, resulting in an error as shown in the screenshot.

If you have updated the next-redux-wrapper to `6.0.0` , downgrade to `6.0.0-rc.7`, delete node_modules, and check it again by `npm i`.

**Comment by wiiler** [comment]
thank you
