### ISSUE TITLE
Consider alternate redux-toolkits instead?

### ISSUE THREAD

**Issue by cuongdevjs** [treetips/typescript-nextjs-redux-material-ui-example#35]

**Comment by treetips** [comment]
@cuongdevjs Thanks for contacting me 😃 

I already have a redux-toolkit version, as linked at the end of the README.md, so please check it out.

https://github.com/treetips/typescript-nextjs-redux-toolkit-material-ui-example

**Comment by cuongdevjs** [comment]
Thanks :)
